### PR TITLE
Add Open Source Monthly

### PR DESCRIPTION
**Pull request by alysonla**
Created a visualization for open source orgs using the Github Archive. :bar_chart: :heart:  

http://alysonla.github.io/open-source-monthly/

open-source-monthly-2

oct-dashboard-fb

top orgs_all

### CODE REVIEW

**Comment by igrigorik** [comment]
@alysonla this is awesome, great work! 

QQ: the data is showing November 2015 for me. Is there a way to switch between months?

**Comment by alysonla** [comment]
@igrigorik thanks!

> QQ: the data is showing November 2015 for me. Is there a way to switch between months?

Right now, it just shows the last month that I've pushed up. I've got a local branch going to change into a jekyll website with posts & commentary for each month. TBD tho. In lieu, here is a [link](https://public.tableau.com/profile/alysonla#!/) to a profile that allows scrolling between months. 

Also btw, recently was accepted to give a talk at OSCON this year: `Data Storytelling using the GitHub Archive.` Will likely feature many of the projects listed on this page. :tada:

**Comment by igrigorik** [comment]
> Right now, it just shows the last month that I've pushed up. I've got a local branch going to change into a jekyll website with posts & commentary for each month. TBD tho. In lieu, here is a link to a profile that allows scrolling between months.

Ah, nice! Should we link to that for time being? Until you get the dedicated site up?

> Also btw, recently was accepted to give a talk at OSCON this year: Data Storytelling using the GitHub Archive. Will likely feature many of the projects listed on this page. :tada:

Oh wow, that's awesome -- congrats! Now I'm super keen to see the presentation! :) /cc @fhoffa

**Comment by alysonla** [comment]
> Should we link to that for time being? Until you get the dedicated site up?

Sure that's fine, I'll update. 

> Now I'm super keen to see the presentation! :)

I'll link here if it gets recorded. :smile:

**Comment by alysonla** [comment]
@igrigorik I had edited the link to point to my profile which allows you to scroll through the prior months - anything else I can do? 

Also one of my colleagues recently shared with me another cool visualization project using GitHub's API data: @donnemartin's https://github.com/donnemartin/viz :ok_hand: :sparkles:

**Comment by igrigorik** [comment]
@alysonla thanks, looks good! One more thing.. looks like I can't merge due to conflict. Can you rebase your update?

**Comment by donnemartin** [comment]
@alysonla thanks for the mention, happy you like it :)

**Comment by alysonla** [comment]
@igrigorik fixed the conflict, apologies it took so long. Now good to merge! 😊

**Comment by igrigorik** [comment]
Great work, thank you!

**Pull request merged**
