### PR TITLE
Add information about Ask GitHub

### PR DESCRIPTION
**Pull request by harishvc**
Add information about Ask GitHub

### CODE REVIEW

**Comment by igrigorik** [comment]
@harishvc can you squash the commits into one? On the Ask GitHub site, what's the syntax? There is one sample query but I'm not sure what else I can/should ask for? :)

**Comment by harishvc** [comment]
@igrigorik Sure I can squash the commits into one. On Ask GitHub site,  just search by repository name (for now) or type 'r' to get predefined report queries - excellent feedback, you got me thinking. I am going to make numerous changes to improve UX. You will hear from me in a few days. Thanks.

**Comment by harishvc** [comment]
@igrigorik squashed commits! [Ask GitHub] (http://askgithub.com) currently searches latest GitHub timeline by repository name and provides a few reports - just type 'r' in the text box for reports. I have also integrated with Typeahead. Feedback welcome. Cheers!

**Comment by harishvc** [comment]
@igrigorik Do you have further questions? Thanks again.

**Comment by igrigorik** [comment]
@harishvc thought I was waiting for you to followup on the UX stuff. Merging, but FWIW, it would really help to provide some context on the page for what you can ask to begin with :)

**Comment by harishvc** [comment]
Thank You! Added information about Ask GitHub and how users can take advantage.  https://github.com/harishvc/githubanalytics/commit/c21ab83c9bbda03265be4a7bc1af458ee6f2a968

**Pull request merged**
